# Deep learning with TensorFlow

### What is Deep learning?
- A type of machine learning based on artificial neural networks in which multiple layers of processing are used to extract progressively higher level features from data.

- Machine learning turnng things(data) into numbers and `finding patterns` in those numbers.

![image.png](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/AI-ML-DL.svg/220px-AI-ML-DL.svg.png)



### Why use Deep learning?
- For complex problem, can you think of all the rule.
- Use ML for anything as long as you can convert it into numbers and program it to find patterns. Literally it could be anything any input or output froms the unverse.

### What deep learning is good for?
- Problem with long list of rules
- Continually changing environments - deep learning can adapt('learn') to new scenarios.
- Discovering insights within large collections of data.

### What deep learning is not good for?
- When you need explanability.
- When traditional approach is better option,
- When error are unacceptable.
- When you don't have much data.


### Machine Learning VS Deep Learning
- Machine Learning
  - It typically perform best on **structure Data**
  - e.g Data in Excel sheet
  - Machine Learning Algorithms (Shallow Algorithms)
    1. Random forest
    2. Naive bayes
    3. Spport vector machine
    4. Many more...

- Deep Learning
  - It typically perform best on **unstructure data**
  - e.g. Natural languge text, Image Identification(Food identification) and sound wave
  - Deep Learning Algorithms
    1. Neural Network
    2. Fully connected neural network
    3. Convolution neural network
    4. Recurrent neural network
    5. Transformer
    6. Many more...




### What are neural network?

Data => Turn Data into Number => Neural network(Learns representation patterns/features/weights) => Representation outputs ==> Convert it into human readable form

![image.png](https://raw.githubusercontent.com/mallajay/Tensorflow-Deep-learning/main/image/1.neural_network.png)


### Anatomy of Neural Networks
![image.png](https://raw.githubusercontent.com/mallajay/Tensorflow-Deep-learning/main/image/2.Anatomy_of_neural_network.png)

### Type of learning
![image.png](https://raw.githubusercontent.com/mallajay/Tensorflow-Deep-learning/main/image/3.type_of_learning.png)





# TensorFlow

### What is TensorFlow?
- End-to-end platfrom for machine learning 
- Write fast deep learning code in python/other accessible language(able to run on GPU/TPU)
- Able to access many pre-built deep learning models(TensofFlow Hub)
- Whole stack: preprocess data, modal data, deploy model in your application
- Originally designed and used in-house by Google(now open-source)

### Why use TensorFlow?
- Easy model building
- Robust ML production anywhere
- Powerful experimentation for research

### What is Tensor?
![image.png](https://raw.githubusercontent.com/mallajay/Tensorflow-Deep-learning/main/image/4.what_is_tensor.png)








# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More Specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.functions (a way to speedup your regular Python functions)
* Using GPU with TensorFlow (or TPU)
* Exercises to try yourself!

## Introduction to tensors

In [3]:
# Import TensorFlow
import tensorflow as tf

print(tf.__version__)

2.8.2


In [4]:
# Create tensor with tf.c
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check the number of dimension of a tensor (ndims stands for number of dimensions)
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimension of our vector
vector.ndim

1

In [9]:
# Create a matrix (has more then one dimension)
matrix = tf.constant([ [10, 7], 
                       [7, 10]
                      ])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [16]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]
                              ], dtype=tf.float16) # specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [17]:
# What's the number dimensions of another_matrix

another_matrix.ndim

2

In [18]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,], 
                       [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]], 
                    [[13, 14, 15],
                     [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [22]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, `a 0-dimesional tensor is a scalar`, `a 1-dimensional tensor is a vector`)